include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
  image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
  variables:
    MANIFEST_PATH: "dist/flatpak/com.gitlab.nahuelwexd.Unitube.json"
    MESON_ARGS: "-Dprofile=development"
    FLATPAK_MODULE: "unitube"
    APP_ID: "com.gitlab.nahuelwexd.Unitube.Devel"
    RUNTIME_REPO: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    BUNDLE: "com.gitlab.nahuelwexd.Unitube.flatpak"
  extends: .flatpak
