image: archlinux/base

stages:
  - arch
  - flatpak

build:
  stage: arch
  script:
    - pacman -Syu --noconfirm sudo
    - useradd builduser -m
    - passwd -d builduser
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
    - sudo -u builduser bash -c 'cd dist/arch && makepkg -s --noconfirm'
  artifacts:
    paths:
      - pkg/

build:
  stage: flatpak
  script:
    - pacman -Syu flatpak flatpak-builder
    - flatpak-builder builddir dist/flatpak/com.gitlab.nahuelwexd.Unitube.json
  artifacts:
    paths:
      - builddir/
