stages:
  - build
  - test

build:
  image: archlinux/base
  stage: build
  script:
    - pacman -Syu vala meson
    - meson build --prefix /usr
    - ninja -C build

test:
  stage: test
  script:
    - ninja -C build test
