on:
  push:
    paths-ignore:
    - .github/FUNDING.yml
    - .editorconfig
    - .gitignore
    - COPYING
    - README.md
    - ui-concept.png
    - Replay.doap
name: Continuous Integration
jobs:
  build:
    name: Build app
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Setup Flatpak environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder valac
        flatpak remote-add --user --if-not-exists gnome-nightly \
            https://nightly.gnome.org/gnome-nightly.flatpakrepo
    - name: Build with Flatpak Builder
      run: |
        ./build-aux/flatpak/generate-replay-constants.vala "${{ secrets.API_KEY }}" \
            src/constants.vala
        flatpak-builder --user --repo=repo --install-deps-from=gnome-nightly flatpak_app \
            build-aux/flatpak/com.github.nahuelwexd.Replay.json
    - uses: actions/upload-artifact@v2
      with:
        name: repo
        path: repo
  package:
    name: Create Flatpak bundle
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - name: Install Flatpak
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y flatpak
    - name: Create Flatpak bundle
      run: |
        flatpak build-bundle repo com.github.nahuelwexd.Replay.Devel.flatpak \
            com.github.nahuelwexd.Replay.Devel
        flatpak build-bundle --runtime repo com.github.nahuelwexd.Replay.Devel.Locale.flatpak \
            com.github.nahuelwexd.Replay.Devel.Locale
    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v2
      with:
        name: Flatpak Bundles
        path: '*.flatpak'
