on:
  push:
    paths-ignore:
    - .github/FUNDING.yml
    - .editorconfig
    - .gitignore
    - COPYING
    - README.md
    - ui-concept.png
    - UniTube-GTK.doap
name: Continuous Integration
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Setup Flatpak environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo add-apt-repository ppa:alexlarsson/flatpak
        sudo apt update
        sudo apt install -y flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install -y --noninteractive flathub org.gnome.Sdk//3.36 org.gnome.Platform//3.36
    - name: Build with Flatpak Builder
      run: |
        flatpak-builder --repo repo flatpak_app build-aux/com.github.nahuelwexd.UniTube.json
    - uses: actions/upload-artifact@v2
      with:
        name: repo
        path: repo
  package:
    name: Create Flatpak bundle
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - name: Install Flatpak
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y flatpak
    - name: Create Flatpak bundle
      run: |
        flatpak build-bundle repo com.github.nahuelwexd.UniTube.Devel.flatpak com.github.nahuelwexd.UniTube.Devel
        flatpak build-bundle --runtime repo com.github.nahuelwexd.Devel.Locale.flatpak com.github.nahuelwexd.UniTube.Devel.Locale
    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v2
      with:
        name: Flatpak Bundle
        path: '*.flatpak'
