on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache .flatpak-builder/downloads folder
      env:
        cache-folder: downloads
      uses: actions/cache@v1
      with:
        path: .flatpak-builder/${{ env.cache-folder }}
        key: ${{ env.cache-folder }}
    - name: Cache .flatpak-builder/git folder
      env:
        cache-folder: git
      uses: actions/cache@v1
      with:
        path: .flatpak-builder/${{ env.cache-folder }}
        key: ${{ env.cache-folder }}
    - name: Build Flatpak bundle
      uses: nahuelwexd/flatpak-builder-action@gnome-3-36
      with:
        manifest-path: build-aux/com.github.nahuelwexd.UniTube.json
        meson-args: -Dprofile=development
        flatpak-module: unitube
        app-id: com.github.nahuelwexd.UniTube.Devel
        bundle: com.github.nahuelwexd.UniTube.Devel.flatpak
    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v1
      with:
        name: Flatpak Bundle
        path: com.github.nahuelwexd.UniTube.Devel.flatpak
    - name: Upload repo tar
      uses: actions/upload-artifact@v1
      with:
        name: Repo
        path: repo.tar
    - name: Upload build logs
      uses: actions/upload-artifact@v1
      with:
        name: Build logs
        path: .flatpak-builder/build/unitube/_flatpak_build/meson-logs/meson-log.txt
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      with:
        name: Test logs
        path: .flatpak-builder/build/unitube/_flatpak_build/meson-logs/testlog.txt
