on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - env:
        cache-folder: downloads
      uses: actions/cache@v1
      with:
        path: .flatpak-builder/${{ env.cache-folder }}
        key: ${{ env.cache-folder }}
    - env:
        cache-folder: git
      uses: actions/cache@v1
      with:
        path: .flatpak-builder/${{ env.cache-folder }}
        key: ${{ env.cache-folder }}
    - name: Flatpak Builder Action
      uses: nahuelwexd/flatpak-builder-action@gnome-3-36
      with:
        manifest-path: build-aux/com.github.nahuelwexd.Unitube.json
        meson-args: -Dprofile=development
        flatpak-module: unitube
        app-id: com.github.nahuelwexd.Unitube.Devel
        bundle: com.github.nahuelwexd.Unitube.Devel.flatpak
    - name: Upload Generated Bundle
      uses: actions/upload-artifact@v1
      with:
        name: Flatpak Bundle
        path: com.github.nahuelwexd.Unitube.Devel.flatpak
