on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      run: docker build -t flatpak-docker build-aux
    - name: Run Docker Image
      run: |
        docker run --privileged --device /dev/fuse --workdir /github/workspace \
          --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA \
          -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW  \
          -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME \
          -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH \
          -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "$GITHUB_WORKSPACE":"/github/workspace" -i flatpak-docker \
            --manifest-path "build-aux/com.gitlab.nahuelwexd.Unitube.json" \
            --app-id "com.gitlab.nahuelwexd.Unitube.Devel" \
            --bundle "com.github.nahuelwexd.Unitube.Devel.flatpak"
